In [2]:
import numpy as np
data=np.random.rand(5)
print(data)
print(data.shape)

[0.11218994 0.5814916  0.82703109 0.6721107  0.05893309]
(5,)


data既不是行向量，也不是列向量  
rank 1 array

In [7]:
print(data)
print(data.T)
print(data==data.T)
print(np.dot(data,data))
print(np.dot(data,data.T))

[0.11218994 0.5814916  0.82703109 0.6721107  0.05893309]
[0.11218994 0.5814916  0.82703109 0.6721107  0.05893309]
[ True  True  True  True  True]
1.4899053905394222
1.4899053905394222


In [10]:
data1=np.random.rand(5,1)
print(data1,data1.T)
print(np.dot(data1.T,data1))
print(np.dot(data1,data1.T))

[[0.34640595]
 [0.39071213]
 [0.69022793]
 [0.97804635]
 [0.87650712]] [[0.34640595 0.39071213 0.69022793 0.97804635 0.87650712]]
[[2.47390705]]
[[0.11999708 0.13534501 0.23909906 0.33880108 0.30362728]
 [0.13534501 0.15265597 0.26968042 0.38213457 0.34246196]
 [0.23909906 0.26968042 0.4764146  0.67507491 0.6049897 ]
 [0.33880108 0.38213457 0.67507491 0.95657467 0.8572646 ]
 [0.30362728 0.34246196 0.6049897  0.8572646  0.76826474]]


确保正确

In [16]:
assert(data1.shape==(5,1))

In [21]:
assert(data.shape==(5,))