In [1]:
import numpy as np
import time

## eg

In [15]:
a=np.random.rand(1000000)
b=np.random.rand(1000000)


non-vectorization

In [25]:
tick=time.time()
c=0
for i in range(1000000):
    c+=a[i]*b[i]
tock=time.time()
print(c)
print("time:",(tock-tick)*1000,"ms",sep='')

250062.23724401137
time:587.4423980712891ms


vectorization

In [123]:

v_a=np.array(a)
v_b=np.array(b)
tick=time.time()
z=np.dot(v_a,v_b)
tock=time.time()
print("time:",(tock-tick)*1000,"ms",sep='')

time:0.9984970092773438ms


In [84]:
tick=time.time()
z=np.dot(a,b)
tock=time.time()
print("time:",(tock-tick)*1000,"ms",sep='')

time:0.9980201721191406ms


# eg

In [145]:
a=np.random.rand(10000)
v=np.zeros((10000))
tick=time.time()
for i in range(10000):
    v[i]=np.exp(a[i])
tock=time.time()
print('time:',(tock-tick)*1000,'ms',sep='')

time:26.919126510620117ms


In [146]:
tick=time.time()
z=np.exp(a)
tock=time.time()
print('time:',(tock-tick)*1000,'ms',sep='')

time:0.9958744049072266ms


In [147]:
z

array([1.0060205 , 1.15321825, 2.00803258, ..., 1.88094869, 1.8304507 ,
       2.09202775])

In [148]:
v

array([1.0060205 , 1.15321825, 2.00803258, ..., 1.88094869, 1.8304507 ,
       2.09202775])

# 广播

In [155]:
import pandas as pd

In [167]:
apple=pd.Series([56,1.2,1.8],index=['carb','protein','fat'])
beef=pd.Series([0,104,35],index=['carb','protein','fat'])
egg=pd.Series([4.4,52,99],index=['carb','protein','fat'])
potato=pd.Series([68,8,0.9],index=['carb','protein','fat'])
t=pd.DataFrame({'apple':apple,'beef':beef,'egg':egg,'potato':potato})

In [186]:
weight=t.sum(axis=0)
p=apple=t/weight
print(p)

            apple      beef       egg    potato
carb     0.949153  0.000000  0.028314  0.884265
protein  0.020339  0.748201  0.334620  0.104031
fat      0.030508  0.251799  0.637066  0.011704


In [188]:
data=np.array(t)
all_weight=np.sum(data,axis=0)
perc=data/all_weight.reshape(1,4)*100
print(perc)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 74.82014388 33.46203346 10.40312094]
 [ 3.05084746 25.17985612 63.70656371  1.17035111]]


# axis=0 y轴，axis=1：x轴

In [190]:
print(all_weight.reshape(1,4))

[[ 59.  139.  155.4  76.9]]


In [207]:
x=np.array([[1,2],
           [10,100]])
y=np.array([[1,2,3,4],
           [5,6,7,8],
           [9,10,11,12],
           [13,14,15,16]])
z=[[1,2,3,4]]
y/z

array([[ 1.        ,  1.        ,  1.        ,  1.        ],
       [ 5.        ,  3.        ,  2.33333333,  2.        ],
       [ 9.        ,  5.        ,  3.66666667,  3.        ],
       [13.        ,  7.        ,  5.        ,  4.        ]])